<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="EndLogic" Id="{71e1561f-8207-47a3-99b7-aa8be5bb6b09}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM EndLogic
VAR
	fbRTRIG: R_TRIG;
	fbRTRIGFillInUpper : R_TRIG;
END_VAR
VAR_INPUT
//	In : INT;
	nCurrentBlock: BOOL;
END_VAR
VAR_OUTPUT
	OutputBool : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

fbRTRIG(CLK:=nCurrentBlock , Q=> ); 

OutputBool := fbRTRIG.Q;]]></ST>
    </Implementation>
    <LineIds Name="EndLogic">
      <LineId Id="20" Count="1" />
      <LineId Id="5" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="6" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>