<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="fbWaitBlock" Id="{b5ed8a97-d186-41dd-948c-47796c432afe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fbWaitBlock IMPLEMENTS IWaitBlock
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="fbWaitBlock">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>