/* Tags for Field Points of Equipments connected to Reactor */
delete from dbo.CommandPoints where CommandPoints.Label in (select Label from dbo.FieldPoints where TypeOfAddress='FieldPoint')
delete from dbo.FieldPoints where TypeOfAddress='FieldPoint'

/* Tags for Reactor 1 */
	INSERT [dbo].[FieldPoints] VALUES (N'BatchName', N'BatchName', N'FieldPoint', N'R1.BatchText_1', N'string', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'BatchNumber', N'BatchNumber', N'FieldPoint', N'R1.BatchText_2', N'string', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'BatchRemarks', N'BatchRemarks', N'FieldPoint', N'R1.BatchText_3', N'string', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'BatchScientistName', N'BatchScientistName', N'FieldPoint', N'R1.BatchText_5', N'string', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'BatchStatus', N'BatchStatus', N'FieldPoint', N'R1.BatchText_4', N'string', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'EmergencyStatus', N'EmergencyStatus', N'FieldPoint', N'R1.EmergencyStatus', N'bool', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_1', N'Pump_1', N'FieldPoint', N'IO.Vessels[0].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_10', N'Pump_10', N'FieldPoint', N'IO.Vessels[0].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_11', N'Pump_11', N'FieldPoint', N'IO.Vessels[2].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_12', N'Pump_12', N'FieldPoint', N'IO.Vessels[3].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_13', N'Pump_13', N'FieldPoint', N'IO.Vessels[5].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_14', N'Pump_14', N'FieldPoint', N'IO.Vessels[6].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_15', N'Pump_15', N'FieldPoint', N'IO.Vessels[8].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_16', N'Pump_16', N'FieldPoint', N'IO.Vessels[1].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_17', N'Pump_17', N'FieldPoint', N'IO.Vessels[7].Pumps[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_2', N'Pump_2', N'FieldPoint', N'IO.Vessels[1].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_3', N'Pump_3', N'FieldPoint', N'IO.Vessels[2].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_4', N'Pump_4', N'FieldPoint', N'IO.Vessels[3].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_5', N'Pump_5', N'FieldPoint', N'IO.Reactors[1].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_6', N'Pump_6', N'FieldPoint', N'IO.Vessels[7].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_7', N'Pump_7', N'FieldPoint', N'IO.Vessels[5].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_8', N'Pump_8', N'FieldPoint', N'IO.Vessels[8].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pump_9', N'Pump_9', N'FieldPoint', N'IO.Vessels[4].Pumps[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'UsedNow', N'Reactor_1|UsedNow', N'FieldPoint', N'R1.UsedNow', N'bool', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_1', N'Valve_1', N'FieldPoint', N'IO.Vessels[0].Valves[0].bStart', N'bool', N'true', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_10', N'Valve_10', N'FieldPoint', N'IO.Vessels[2].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_11', N'Valve_11', N'FieldPoint', N'IO.Vessels[2].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_12', N'Valve_12', N'FieldPoint', N'IO.Vessels[3].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_13', N'Valve_13', N'FieldPoint', N'IO.Vessels[3].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_14', N'Valve_14', N'FieldPoint', N'IO.Vessels[3].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_15', N'Valve_15', N'FieldPoint', N'IO.Vessels[3].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_16', N'Valve_16', N'FieldPoint', N'IO.Vessels[5].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_17', N'Valve_17', N'FieldPoint', N'IO.Vessels[5].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_18', N'Valve_18', N'FieldPoint', N'IO.Vessels[5].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_19', N'Valve_19', N'FieldPoint', N'IO.Vessels[5].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_2', N'Valve_2', N'FieldPoint', N'IO.Vessels[0].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_20', N'Valve_20', N'FieldPoint', N'IO.Vessels[5].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_21', N'Valve_21', N'FieldPoint', N'IO.Vessels[6].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_22', N'Valve_22', N'FieldPoint', N'IO.Vessels[6].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_23', N'Valve_23', N'FieldPoint', N'IO.Vessels[6].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_24', N'Valve_24', N'FieldPoint', N'IO.Vessels[6].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_25', N'Valve_25', N'FieldPoint', N'IO.Vessels[6].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_26', N'Valve_26', N'FieldPoint', N'IO.Reactors[1].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_27', N'Valve_27', N'FieldPoint', N'IO.Reactors[1].Valves[6].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_28', N'Valve_28', N'FieldPoint', N'IO.Reactors[1].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_29', N'Valve_29', N'FieldPoint', N'IO.Reactors[1].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_3', N'Valve_3', N'FieldPoint', N'IO.Vessels[0].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_30', N'Valve_30', N'FieldPoint', N'IO.Reactors[1].Valves[5].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_31', N'Valve_31', N'FieldPoint', N'IO.Reactors[1].Valves[7].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_32', N'Valve_32', N'FieldPoint', N'IO.Vessels[7].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_33', N'Valve_33', N'FieldPoint', N'IO.Vessels[7].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_34', N'Valve_34', N'FieldPoint', N'IO.Vessels[7].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_35', N'Valve_35', N'FieldPoint', N'IO.Vessels[7].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_36', N'Valve_36', N'FieldPoint', N'IO.Vessels[7].Valves[6].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_37', N'Valve_37', N'FieldPoint', N'IO.Reactors[0].Valves[6].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_38', N'Valve_38', N'FieldPoint', N'IO.Reactors[0].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_39', N'Valve_39', N'FieldPoint', N'IO.Reactors[0].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_4', N'Valve_4', N'FieldPoint', N'IO.Vessels[1].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_40', N'Valve_40', N'FieldPoint', N'IO.Vessels[0].Valves[5].bStart', N'bool', N'true', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_41', N'Valve_41', N'FieldPoint', N'IO.Vessels[0].Valves[6].bStart', N'bool', N'true', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_42', N'Valve_42', N'FieldPoint', N'IO.Reactors[0].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_43', N'Valve_43', N'FieldPoint', N'IO.Vessels[8].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_44', N'Valve_44', N'FieldPoint', N'IO.Vessels[8].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_45', N'Valve_45', N'FieldPoint', N'IO.Vessels[8].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_46', N'Valve_46', N'FieldPoint', N'IO.Vessels[8].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_47', N'Valve_47', N'FieldPoint', N'IO.Vessels[4].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_48', N'Valve_48', N'FieldPoint', N'IO.Vessels[4].Valves[4].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_49', N'Valve_49', N'FieldPoint', N'IO.Vessels[4].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_5', N'Valve_5', N'FieldPoint', N'IO.Vessels[1].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_50', N'Valve_50', N'FieldPoint', N'IO.Vessels[4].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_51', N'Valve_51', N'FieldPoint', N'IO.Reactors[1].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_52', N'Valve_52', N'FieldPoint', N'IO.Reactors[0].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_53', N'Valve_53', N'FieldPoint', N'IO.Vessels[0].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_54', N'Valve_54', N'FieldPoint', N'IO.Vessels[2].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_55', N'Valve_55', N'FieldPoint', N'IO.Vessels[3].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_56', N'Valve_56', N'FieldPoint', N'IO.Reactors[0].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_57', N'Valve_57', N'FieldPoint', N'IO.Reactors[0].Valves[5].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_58', N'Valve_58', N'FieldPoint', N'IO.Vessels[4].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_59', N'Valve_59', N'FieldPoint', N'IO.Vessels[5].Valves[5].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_6', N'Valve_6', N'FieldPoint', N'IO.Vessels[1].Valves[3].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_60', N'Valve_60', N'FieldPoint', N'IO.Vessels[5].Valves[6].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_61', N'Valve_61', N'FieldPoint', N'IO.Vessels[6].Valves[5].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_62', N'Valve_61', N'FieldPoint', N'IO.Vessels[6].Valves[6].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_7', N'Valve_7', N'FieldPoint', N'IO.Vessels[1].Valves[2].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_8', N'Valve_8', N'FieldPoint', N'IO.Vessels[2].Valves[0].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Valve_9', N'Valve_9', N'FieldPoint', N'IO.Vessels[2].Valves[1].bStart', N'bool', N'false', N'false', N'sensorDataSet_1', N'Reactor_1')

	INSERT [dbo].[FieldPoints] VALUES (N'StirrerFeedback_1', N'StirrerFeedback_1', N'FieldPoint', N'IO.Reactors[0].VFD.nRPMFeedBackScaled', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'StirrerFeedback_2', N'StirrerFeedback_2', N'FieldPoint', N'IO.Reactors[0].VFD.nRPMFeedBackScaled', N'single', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')

	INSERT [dbo].[FieldPoints] VALUES (N'StirrerCommand_1', N'StirrerCommand_1', N'FieldPoint', N'IO.StirrerCommand_1', N'bool', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'StirrerCommand_2', N'StirrerCommand_2', N'FieldPoint', N'IO.StirrerCommand_2', N'bool', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pressure_1', N'Pressure_1', N'FieldPoint', N'IO.Pressure_1', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Pressure_2', N'Pressure_2', N'FieldPoint', N'IO.Pressure_2', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Temperature_1', N'Temperature_1', N'FieldPoint', N'IO.Temperature_1', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'Temperature_2', N'Temperature_2', N'FieldPoint', N'IO.Temperature_2', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'ReactorLevel_1', N'ReactorLevel_1', N'FieldPoint', N'IO.ReactorLevel_1', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'ReactorLevel_2', N'ReactorLevel_2', N'FieldPoint', N'IO.ReactorLevel_2', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'StirrerSetpoint_1', N'StirrerSetpoint_1', N'FieldPoint', N'IO.Reactors[1].VFD.nRPMSetPointScaled', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'StirrerSetpoint_2', N'StirrerSetpoint_2', N'FieldPoint', N'IO.Reactors[0].VFD.nRPMSetPointScaled', N'double', N'false', N'true', N'sensorDataSet_1', N'Reactor_1')

	insert into dbo.CommandPoints select Label, SensorDataSetIdentifier, FieldDeviceIdentifier from dbo.FieldPoints
	where CHARINDEX('Valve_', Label) > 0 or CHARINDEX('Pump_', Label) > 0 or CHARINDEX('StirrerCommand_', Label) > 0 or CHARINDEX('StirrerSetpoint_', Label) > 0




	INSERT [dbo].[FieldPoints] VALUES (N'HeatCoolSetPoint', N'HeatCoolSetPoint', N'FieldPoint', N'IO.Temperature_1', N'double', N'true', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'JacketOutletTemperature', N'JacketOutletTemperature', N'FieldPoint', N'IO.Temperature_1', N'double', N'true', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'ReactorPressure', N'ReactorPressure', N'FieldPoint', N'IO.Temperature_1', N'double', N'true', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'ReactorTemperature', N'ReactorTemperature', N'FieldPoint', N'IO.Temperature_1', N'double', N'true', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'VapourTemperature', N'VapourTemperature', N'FieldPoint', N'IO.Temperature_1', N'double', N'true', N'true', N'sensorDataSet_1', N'Reactor_1')
	INSERT [dbo].[FieldPoints] VALUES (N'VentTemperature', N'VentTemperature', N'FieldPoint', N'IO.Temperature_1', N'double', N'true', N'true', N'sensorDataSet_1', N'Reactor_1')


